import type { SiteSettingsRow } from "@/lib/schema";

export const DEFAULT_SITE_SETTINGS: SiteSettingsRow = {
  id: 1,
  logoUrl: null,
  logoAlt: null,
  logoSizePx: 160,
  headerLayout: "side",
  headerPlacement: "split",
  brandLine1: "WSU",
  brandLine2: "Grad",
  headerTitle: "Graduate School Tools",
  headerSubtitle: "Internal directory",
  headerTitleSizePx: 28,
  headerTextPaddingTopPx: 0,
  headerTextPaddingBottomPx: 0,
  headerTextPaddingLeftPx: 0,
  headerTextPaddingRightPx: 0,
  headerTitleSubtitleGapPx: 4,
  heroTitle: "Applications",
  heroLede:
    "This directory is public. Use Manage apps to sign in and update links, descriptions, ordering, and branding.",
  emptyStateText: "No applications yet. Use Manage apps to add the first card.",
  manageAddTitle: "Add application",
  manageAddBlurb:
    "Create a new directory card with a title, action label, URL, and optional description.",
  manageOrderTitle: "Your cards",
  manageOrderBlurb: "Edit or remove any card, or drag the handle to change the public page order.",
  manageEmptyDragText: "No cards yet. Use the form below to add the first application.",
  loginTitle: "Sign in to manage the directory",
  loginLede:
    "Use the shared admin password to edit cards, update branding, and manage the header logo. You will land on the manage page after you sign in.",
  loginBackLabel: "Back to directory",
  colorPrimary: "#981e32",
  colorPrimaryDark: "#6d1524",
  colorText: "#393939",
  colorTextMuted: "#5e6a71",
  colorBorder: "#e2e2e2",
  colorPageBg: "#f7f5f5",
  colorCardBg: "#ffffff",
  colorCardBorder: "#e2e2e2",
  colorCardAccent: "#981e32",
  colorCardTitle: "#393939",
  colorCardDescription: "#5e6a71",
  colorUrlOnCard: "#981e32",
  cardFontFamily: "montserrat",
  cardActionFontFamily: "match-card",
  cardActionFontWeight: "700",
  cardTitleSizePx: 16,
  cardUrlSizePx: 12,
  cardDescriptionSizePx: 14,
  cardPaddingPx: 20,
  cardAccentHeightPx: 6,
  cardRadiusPx: 10,
  cardShadow: "md",
  gridColumns: 3,
  updatedAt: null,
};
