CREATE TABLE "app_card" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"url" text NOT NULL,
	"description" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "site_settings" (
	"id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
	"logo_url" text,
	"logo_alt" text,
	"logo_size_px" integer DEFAULT 160 NOT NULL,
	"header_layout" text DEFAULT 'side' NOT NULL,
	"brand_line1" text,
	"brand_line2" text,
	"header_title" text,
	"header_subtitle" text,
	"header_title_size_px" integer,
	"hero_title" text,
	"hero_lede" text,
	"empty_state_text" text,
	"manage_add_title" text,
	"manage_add_blurb" text,
	"manage_order_title" text,
	"manage_order_blurb" text,
	"manage_empty_drag_text" text,
	"login_title" text,
	"login_lede" text,
	"login_back_label" text,
	"color_primary" text DEFAULT '#981e32' NOT NULL,
	"color_primary_dark" text DEFAULT '#6d1524' NOT NULL,
	"color_text" text DEFAULT '#393939' NOT NULL,
	"color_text_muted" text DEFAULT '#5e6a71' NOT NULL,
	"color_border" text DEFAULT '#e2e2e2' NOT NULL,
	"color_page_bg" text DEFAULT '#f7f5f5' NOT NULL,
	"color_card_bg" text DEFAULT '#ffffff' NOT NULL,
	"color_card_accent" text DEFAULT '#981e32' NOT NULL,
	"color_url_on_card" text DEFAULT '#981e32' NOT NULL,
	"card_radius_px" integer DEFAULT 10 NOT NULL,
	"card_shadow" text DEFAULT 'md' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now()
);
