CREATE TABLE IF NOT EXISTS "app_card" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "title" text NOT NULL,
  "url" text NOT NULL,
  "description" text,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "site_settings" (
  "id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
  "logo_url" text,
  "logo_alt" text,
  "logo_size_px" integer DEFAULT 160 NOT NULL,
  "header_layout" text DEFAULT 'side' NOT NULL,
  "brand_line1" text,
  "brand_line2" text,
  "header_title" text,
  "header_subtitle" text,
  "header_title_size_px" integer,
  "hero_title" text,
  "hero_lede" text,
  "empty_state_text" text,
  "manage_add_title" text,
  "manage_add_blurb" text,
  "manage_order_title" text,
  "manage_order_blurb" text,
  "manage_empty_drag_text" text,
  "login_title" text,
  "login_lede" text,
  "login_back_label" text,
  "color_primary" text DEFAULT '#981e32' NOT NULL,
  "color_primary_dark" text DEFAULT '#6d1524' NOT NULL,
  "color_text" text DEFAULT '#393939' NOT NULL,
  "color_text_muted" text DEFAULT '#5e6a71' NOT NULL,
  "color_border" text DEFAULT '#e2e2e2' NOT NULL,
  "color_page_bg" text DEFAULT '#f7f5f5' NOT NULL,
  "color_card_bg" text DEFAULT '#ffffff' NOT NULL,
  "color_card_accent" text DEFAULT '#981e32' NOT NULL,
  "color_url_on_card" text DEFAULT '#981e32' NOT NULL,
  "card_radius_px" integer DEFAULT 10 NOT NULL,
  "card_shadow" text DEFAULT 'md' NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now()
);

INSERT INTO "site_settings" (
  "id",
  "logo_url",
  "logo_alt",
  "logo_size_px",
  "header_layout",
  "brand_line1",
  "brand_line2",
  "header_title",
  "header_subtitle",
  "header_title_size_px",
  "hero_title",
  "hero_lede",
  "empty_state_text",
  "manage_add_title",
  "manage_add_blurb",
  "manage_order_title",
  "manage_order_blurb",
  "manage_empty_drag_text",
  "login_title",
  "login_lede",
  "login_back_label",
  "color_primary",
  "color_primary_dark",
  "color_text",
  "color_text_muted",
  "color_border",
  "color_page_bg",
  "color_card_bg",
  "color_card_accent",
  "color_url_on_card",
  "card_radius_px",
  "card_shadow"
) VALUES (
  1,
  NULL,
  NULL,
  160,
  'side',
  'WSU',
  'Grad',
  'Graduate School Tools',
  'Internal directory',
  28,
  'Applications',
  'This directory is public. Use Manage apps to sign in and update links, descriptions, ordering, and branding.',
  'No applications yet. Use Manage apps to add the first card.',
  'Add application',
  'Add a title and URL for each application. Descriptions and branding are optional. Reorder cards below and changes save automatically.',
  'Card order',
  'Drag by the handle. The order here matches the public landing page.',
  'No cards yet. Add one above.',
  'Sign in to manage the directory',
  'Use the shared admin password to edit cards, update branding, and manage the header logo. You will land on the manage page after you sign in.',
  'Back to directory',
  '#981e32',
  '#6d1524',
  '#393939',
  '#5e6a71',
  '#e2e2e2',
  '#f7f5f5',
  '#ffffff',
  '#981e32',
  '#981e32',
  10,
  'md'
)
ON CONFLICT ("id") DO NOTHING;
