CREATE TABLE IF NOT EXISTS "app_card" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "title" text NOT NULL,
  "action_label" text DEFAULT 'Open tool' NOT NULL,
  "url" text NOT NULL,
  "description" text,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "site_settings" (
  "id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
  "logo_url" text,
  "logo_alt" text,
  "logo_size_px" integer DEFAULT 160 NOT NULL,
  "header_layout" text DEFAULT 'side' NOT NULL,
  "header_placement" text DEFAULT 'split' NOT NULL,
  "brand_line1" text,
  "brand_line2" text,
  "header_title" text,
  "header_subtitle" text,
  "header_title_size_px" integer,
  "header_text_padding_top_px" integer DEFAULT 0 NOT NULL,
  "header_text_padding_bottom_px" integer DEFAULT 0 NOT NULL,
  "header_text_padding_left_px" integer DEFAULT 0 NOT NULL,
  "header_text_padding_right_px" integer DEFAULT 0 NOT NULL,
  "header_title_subtitle_gap_px" integer DEFAULT 4 NOT NULL,
  "hero_title" text,
  "hero_lede" text,
  "empty_state_text" text,
  "manage_add_title" text,
  "manage_add_blurb" text,
  "manage_order_title" text,
  "manage_order_blurb" text,
  "manage_empty_drag_text" text,
  "login_title" text,
  "login_lede" text,
  "login_back_label" text,
  "color_primary" text DEFAULT '#981e32' NOT NULL,
  "color_primary_dark" text DEFAULT '#6d1524' NOT NULL,
  "color_text" text DEFAULT '#393939' NOT NULL,
  "color_text_muted" text DEFAULT '#5e6a71' NOT NULL,
  "color_border" text DEFAULT '#e2e2e2' NOT NULL,
  "color_page_bg" text DEFAULT '#f7f5f5' NOT NULL,
  "color_card_bg" text DEFAULT '#ffffff' NOT NULL,
  "color_card_border" text DEFAULT '#e2e2e2' NOT NULL,
  "color_card_accent" text DEFAULT '#981e32' NOT NULL,
  "color_card_title" text DEFAULT '#393939' NOT NULL,
  "color_card_description" text DEFAULT '#5e6a71' NOT NULL,
  "color_url_on_card" text DEFAULT '#981e32' NOT NULL,
  "card_font_family" text DEFAULT 'montserrat' NOT NULL,
  "card_action_font_family" text DEFAULT 'match-card' NOT NULL,
  "card_action_font_weight" text DEFAULT '700' NOT NULL,
  "card_title_size_px" integer DEFAULT 16 NOT NULL,
  "card_url_size_px" integer DEFAULT 12 NOT NULL,
  "card_description_size_px" integer DEFAULT 14 NOT NULL,
  "card_padding_px" integer DEFAULT 20 NOT NULL,
  "card_accent_height_px" integer DEFAULT 6 NOT NULL,
  "card_radius_px" integer DEFAULT 10 NOT NULL,
  "card_shadow" text DEFAULT 'md' NOT NULL,
  "grid_columns" integer DEFAULT 3 NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now()
);

INSERT INTO "site_settings" (
  "id",
  "logo_url",
  "logo_alt",
  "logo_size_px",
  "header_layout",
  "header_placement",
  "brand_line1",
  "brand_line2",
  "header_title",
  "header_subtitle",
  "header_title_size_px",
  "header_text_padding_top_px",
  "header_text_padding_bottom_px",
  "header_text_padding_left_px",
  "header_text_padding_right_px",
  "header_title_subtitle_gap_px",
  "hero_title",
  "hero_lede",
  "empty_state_text",
  "manage_add_title",
  "manage_add_blurb",
  "manage_order_title",
  "manage_order_blurb",
  "manage_empty_drag_text",
  "login_title",
  "login_lede",
  "login_back_label",
  "color_primary",
  "color_primary_dark",
  "color_text",
  "color_text_muted",
  "color_border",
  "color_page_bg",
  "color_card_bg",
  "color_card_border",
  "color_card_accent",
  "color_card_title",
  "color_card_description",
  "color_url_on_card",
  "card_font_family",
  "card_action_font_family",
  "card_action_font_weight",
  "card_title_size_px",
  "card_url_size_px",
  "card_description_size_px",
  "card_padding_px",
  "card_accent_height_px",
  "card_radius_px",
  "card_shadow",
  "grid_columns"
) VALUES (
  1,
  NULL,
  NULL,
  160,
  'side',
  'split',
  'WSU',
  'Grad',
  'Graduate School Tools',
  'Internal directory',
  28,
  0,
  0,
  0,
  0,
  4,
  'Applications',
  'This directory is public. Use Manage apps to sign in and update links, descriptions, ordering, and branding.',
  'No applications yet. Use Manage apps to add the first card.',
  'Add application',
  'Create a new directory card with a title, action label, URL, and optional description.',
  'Your cards',
  'Edit or remove any card, or drag the handle to change the public page order.',
  'No cards yet. Use the form below to add the first application.',
  'Sign in to manage the directory',
  'Use the shared admin password to edit cards, update branding, and manage the header logo. You will land on the manage page after you sign in.',
  'Back to directory',
  '#981e32',
  '#6d1524',
  '#393939',
  '#5e6a71',
  '#e2e2e2',
  '#f7f5f5',
  '#ffffff',
  '#e2e2e2',
  '#981e32',
  '#393939',
  '#5e6a71',
  '#981e32',
  'montserrat',
  'match-card',
  '700',
  16,
  12,
  14,
  20,
  6,
  10,
  'md',
  3
)
ON CONFLICT ("id") DO NOTHING;
